#! /bin/bash

sudo apt install -y i3blocks rofi i3lock arandr feh

# light
cd ~/git
rm -rf light
mkdir lightTemp
cd lightTemp
wget https://github.com/haikarainen/light/tarball/master -O light.tar.gz
tar xf light.tar.gz
rm light.tar.gz
mv * ../light
cd ..
rm -r lightTemp
cd light
./autogen.sh
./configure && make
sudo make install

# picom
cd ~/git
rm -rf picom
sudo apt-get install -y libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev  libpcre2-dev  libevdev-dev uthash-dev libev-dev libx11-xcb-dev libpcre3-dev

git clone https://github.com/yshui/picom.git
cd picom
git submodule update --init --recursive
meson --buildtype=release . build
ninja -C build
sudo ninja -C build install
