#! /bin/bash

# light
cd ~/git
rm -rf light
mkdir lightTemp
cd lightTemp
wget https://github.com/haikarainen/light/tarball/master -O light.tar.gz
tar xf light.tar.gz
rm light.tar.gz
mv * ../light
cd ..
rm -r lightTemp
cd light
./autogen.sh
./configure && make
sudo make install
