#! /bin/bash

set -e

URL="https://installers.privateinternetaccess.com/download/pia-linux-1.6-03756.run"
FILE="pia-linux-1.6-03756.run"

cd ~/Downloads 
#wget "$URL" -O "$FILE"
echo "d0d8f32641b4db04251c5d221334fa7d263f0752f7ab6fa01e72044b5a0d258e $FILE" | sha256sum -c
bash $FILE
